Main svc
Kriglzz/java-explore-with-me pull request #2
Opened 2024-08-11 09:09 UTC by Kriglzz

Main svc

2024-08-12 18:21 UTC, andrew-larkin requested changes
Привет! Отлично, качественная работа, чистый код и много удачных решений. Небольшие правки по коду внести и можно будет приступать к финальному этапу.

2024-08-12 18:21 UTC, andrew-larkin commented on ewm-main-service/src/main/java/ru/practicum/category/service/CategoryService.java
> +@Service
аннотация уже стоит над реализацией интерфейса

2024-08-12 18:21 UTC, andrew-larkin commented on ewm-main-service/src/main/java/ru/practicum/compilations/dto/CompilationUpdateDto.java
> +    private List<Long> events = List.of();
а в других dto этого нет, может, и тут не нужно?

2024-08-12 18:21 UTC, andrew-larkin commented on ewm-main-service/src/main/java/ru/practicum/events/dto/EventDto.java
> +    private Location location;
для Location отдельный dto надо создать

2024-08-12 18:21 UTC, andrew-larkin commented on docker-compose.yml
>      image: postgres:16.1-alpine
для БД нужно также настроить volumes

2024-08-12 18:21 UTC, andrew-larkin commented on docker-compose.yml
> +      - STATISTIC_SERVER_URL=http://stats-server:9090
для сервисов стоит добавить настройку restart on failure

2024-08-12 20:09 UTC, Kriglzz commented on ewm-main-service/src/main/java/ru/practicum/compilations/dto/CompilationUpdateDto.java
> +    private List<Long> events = List.of();
Это для одного теста, потому что там Null значение передается, которое ловится в ошибке
![image](https://github.com/user-attachments/assets/02bda614-cebc-41cf-ad1e-36018530ec09)

2024-08-13 17:53 UTC, andrew-larkin approved these changes
Отлично, работа принята!

2024-08-13 18:34 UTC, merged